; Listing generated by Microsoft (R) Optimizing Compiler Version 19.26.28806.0 

	TITLE	D:\liuyu\task\Auxiliary_maintenance\Win32\Debug\moc\moc_vedio_query.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG409624 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+7
$SG409625 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG409626 DB	'qRegisterNormalizedMetaType', 00H
$SG393388 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG393389 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG401582 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG393390 DB	'qRegisterNormalizedMetaType', 00H
$SG401583 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG401584 DB	'qRegisterNormalizedMetaType', 00H
$SG426248 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG426249 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG426250 DB	'qRegisterNormalizedMetaType', 00H
$SG418122 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG418123 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG418124 DB	'qRegisterNormalizedMetaType', 00H
$SG409978 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG409979 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG409980 DB	'qRegisterNormalizedMetaType', 00H
$SG385514 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG385515 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG385516 DB	'qRegisterNormalizedMetaType', 00H
$SG393716 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG393717 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG401910 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG393718 DB	'qRegisterNormalizedMetaType', 00H
$SG401911 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG401912 DB	'qRegisterNormalizedMetaType', 00H
$SG426602 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG426603 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG426604 DB	'qRegisterNormalizedMetaType', 00H
$SG418450 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG418451 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG418452 DB	'qRegisterNormalizedMetaType', 00H
$SG410332 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG410333 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG410334 DB	'qRegisterNormalizedMetaType', 00H
$SG385842 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG385843 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG385844 DB	'qRegisterNormalizedMetaType', 00H
$SG402238 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG402239 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG402240 DB	'qRegisterNormalizedMetaType', 00H
$SG394075 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG394076 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG394077 DB	'qRegisterNormalizedMetaType', 00H
$SG426956 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG426957 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG426958 DB	'qRegisterNormalizedMetaType', 00H
$SG418804 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG418805 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG418806 DB	'qRegisterNormalizedMetaType', 00H
$SG410686 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG410687 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG410688 DB	'qRegisterNormalizedMetaType', 00H
$SG386170 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG386171 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG386172 DB	'qRegisterNormalizedMetaType', 00H
$SG402592 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG402593 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG402594 DB	'qRegisterNormalizedMetaType', 00H
$SG394403 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG394404 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG394405 DB	'qRegisterNormalizedMetaType', 00H
$SG427310 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG427311 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG427312 DB	'qRegisterNormalizedMetaType', 00H
$SG419158 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG419159 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG419160 DB	'qRegisterNormalizedMetaType', 00H
$SG411040 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG411041 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG411042 DB	'qRegisterNormalizedMetaType', 00H
$SG394731 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG394732 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG394733 DB	'qRegisterNormalizedMetaType', 00H
$SG402946 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG402947 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG402948 DB	'qRegisterNormalizedMetaType', 00H
$SG427664 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG427665 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG427666 DB	'qRegisterNormalizedMetaType', 00H
$SG419512 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG419513 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG419514 DB	'qRegisterNormalizedMetaType', 00H
$SG411394 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG411395 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG411396 DB	'qRegisterNormalizedMetaType', 00H
$SG395059 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG395060 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG395061 DB	'qRegisterNormalizedMetaType', 00H
$SG403274 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG403275 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG403276 DB	'qRegisterNormalizedMetaType', 00H
$SG386977 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG386978 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG386979 DB	'qRegisterNormalizedMetaType', 00H
$SG428018 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG428019 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG428020 DB	'qRegisterNormalizedMetaType', 00H
$SG419865 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG419866 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG419867 DB	'qRegisterNormalizedMetaType', 00H
$SG411748 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG411749 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG411750 DB	'qRegisterNormalizedMetaType', 00H
$SG395387 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG395388 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG395389 DB	'qRegisterNormalizedMetaType', 00H
$SG403628 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG403629 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG403630 DB	'qRegisterNormalizedMetaType', 00H
$SG387331 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG387332 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG387333 DB	'qRegisterNormalizedMetaType', 00H
$SG428372 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG428373 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG428374 DB	'qRegisterNormalizedMetaType', 00H
$SG420220 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG420221 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG420222 DB	'qRegisterNormalizedMetaType', 00H
$SG412102 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG412103 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG412104 DB	'qRegisterNormalizedMetaType', 00H
$SG395721 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG395722 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG395723 DB	'qRegisterNormalizedMetaType', 00H
$SG403982 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG403983 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG403984 DB	'qRegisterNormalizedMetaType', 00H
$SG387659 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG387660 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG387661 DB	'qRegisterNormalizedMetaType', 00H
$SG428726 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG428727 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG428728 DB	'qRegisterNormalizedMetaType', 00H
$SG420573 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG420574 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG420575 DB	'qRegisterNormalizedMetaType', 00H
$SG396049 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG396050 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG396051 DB	'qRegisterNormalizedMetaType', 00H
$SG412456 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG412457 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG412458 DB	'qRegisterNormalizedMetaType', 00H
$SG404310 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG404311 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG404312 DB	'qRegisterNormalizedMetaType', 00H
$SG387987 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG387988 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG387989 DB	'qRegisterNormalizedMetaType', 00H
$SG379824 DB	'containers incompatible for swap', 00H
	ORG $+3
$SG379825 DB	'%s', 00H
	ORG $+1
$SG429080 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG379826 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Prof'
	DB	'essional\VC\Tools\MSVC\14.26.28801\include\xmemory', 00H
	ORG $+1
$SG429082 DB	'qRegisterNormalizedMetaType', 00H
$SG379827 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'P', 00H, 'r', 00H, 'o', 00H, 'f', 00H, 'e', 00H, 's', 00H
	DB	's', 00H, 'i', 00H, 'o', 00H, 'n', 00H, 'a', 00H, 'l', 00H, '\'
	DB	00H, 'V', 00H, 'C', 00H, '\', 00H, 'T', 00H, 'o', 00H, 'o', 00H
	DB	'l', 00H, 's', 00H, '\', 00H, 'M', 00H, 'S', 00H, 'V', 00H, 'C'
	DB	00H, '\', 00H, '1', 00H, '4', 00H, '.', 00H, '2', 00H, '6', 00H
	DB	'.', 00H, '2', 00H, '8', 00H, '8', 00H, '0', 00H, '1', 00H, '\'
	DB	00H, 'i', 00H, 'n', 00H, 'c', 00H, 'l', 00H, 'u', 00H, 'd', 00H
	DB	'e', 00H, '\', 00H, 'x', 00H, 'm', 00H, 'e', 00H, 'm', 00H, 'o'
	DB	00H, 'r', 00H, 'y', 00H, 00H, 00H
	ORG $+2
$SG379828 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'P', 00H, 'o', 00H, 'c', 00H, 's', 00H, 00H, 00H
	ORG $+2
$SG379829 DB	'"', 00H, 'c', 00H, 'o', 00H, 'n', 00H, 't', 00H, 'a', 00H
	DB	'i', 00H, 'n', 00H, 'e', 00H, 'r', 00H, 's', 00H, ' ', 00H, 'i'
	DB	00H, 'n', 00H, 'c', 00H, 'o', 00H, 'm', 00H, 'p', 00H, 'a', 00H
	DB	't', 00H, 'i', 00H, 'b', 00H, 'l', 00H, 'e', 00H, ' ', 00H, 'f'
	DB	00H, 'o', 00H, 'r', 00H, ' ', 00H, 's', 00H, 'w', 00H, 'a', 00H
	DB	'p', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG429081 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG420927 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG420929 DB	'qRegisterNormalizedMetaType', 00H
$SG420928 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG396402 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG396404 DB	'qRegisterNormalizedMetaType', 00H
$SG396403 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG412810 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG412812 DB	'qRegisterNormalizedMetaType', 00H
$SG412811 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG404664 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG404666 DB	'qRegisterNormalizedMetaType', 00H
$SG404665 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG388315 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG388317 DB	'qRegisterNormalizedMetaType', 00H
$SG388316 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG429433 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG429435 DB	'qRegisterNormalizedMetaType', 00H
$SG429434 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG421281 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG421283 DB	'qRegisterNormalizedMetaType', 00H
$SG421282 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG396756 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG396758 DB	'qRegisterNormalizedMetaType', 00H
$SG396757 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG413164 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG413166 DB	'qRegisterNormalizedMetaType', 00H
$SG413165 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG405018 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG405020 DB	'qRegisterNormalizedMetaType', 00H
$SG405019 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG388668 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG388670 DB	'qRegisterNormalizedMetaType', 00H
$SG388669 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG380559 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG380561 DB	'qRegisterNormalizedMetaType', 00H
$SG380560 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG429786 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG429788 DB	'qRegisterNormalizedMetaType', 00H
$SG429787 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG421635 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG421637 DB	'qRegisterNormalizedMetaType', 00H
$SG421636 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG397110 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG397112 DB	'qRegisterNormalizedMetaType', 00H
$SG397111 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG413518 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG413520 DB	'qRegisterNormalizedMetaType', 00H
$SG413519 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG405372 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG405374 DB	'qRegisterNormalizedMetaType', 00H
$SG405373 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG388996 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG388998 DB	'qRegisterNormalizedMetaType', 00H
$SG388997 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG430141 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG430143 DB	'qRegisterNormalizedMetaType', 00H
$SG430142 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG421989 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG421991 DB	'qRegisterNormalizedMetaType', 00H
$SG421990 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG397465 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG397467 DB	'qRegisterNormalizedMetaType', 00H
$SG397466 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG413872 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG413874 DB	'qRegisterNormalizedMetaType', 00H
$SG413873 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG389324 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG389326 DB	'qRegisterNormalizedMetaType', 00H
$SG389325 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG405726 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG405728 DB	'qRegisterNormalizedMetaType', 00H
$SG405727 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG430495 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG430497 DB	'qRegisterNormalizedMetaType', 00H
$SG430496 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG422342 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG422344 DB	'qRegisterNormalizedMetaType', 00H
$SG422343 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG397793 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG397795 DB	'qRegisterNormalizedMetaType', 00H
$SG397794 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG414226 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG414228 DB	'qRegisterNormalizedMetaType', 00H
$SG414227 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG389652 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG389654 DB	'qRegisterNormalizedMetaType', 00H
$SG389653 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG406080 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG406082 DB	'qRegisterNormalizedMetaType', 00H
$SG406081 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG430854 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG430856 DB	'qRegisterNormalizedMetaType', 00H
$SG430855 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG422697 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG422699 DB	'qRegisterNormalizedMetaType', 00H
$SG422698 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG398147 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG398149 DB	'qRegisterNormalizedMetaType', 00H
$SG398148 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG414580 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG414582 DB	'qRegisterNormalizedMetaType', 00H
$SG414581 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG406434 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG406436 DB	'qRegisterNormalizedMetaType', 00H
$SG406435 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
?qt_meta_stringdata_vedio_query@@3Uqt_meta_stringdata_vedio_query_t@@B DD 0ffffffffH ; qt_meta_stringdata_vedio_query
	DD	0bH
	DD	00H
	DD	070H
	DD	0ffffffffH
	DD	08H
	DD	00H
	DD	06cH
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	065H
	DD	0ffffffffH
	DD	011H
	DD	00H
	DD	056H
	DD	0ffffffffH
	DD	0fH
	DD	00H
	DD	058H
	DD	0ffffffffH
	DD	015H
	DD	00H
	DD	058H
	DD	0ffffffffH
	DD	0fH
	DD	00H
	DD	05eH
	DB	076H
	DB	065H
	DB	064H
	DB	069H
	DB	06fH
	DB	05fH
	DB	071H
	DB	075H
	DB	065H
	DB	072H
	DB	079H
	DB	00H
	DB	04fH
	DB	06eH
	DB	053H
	DB	06cH
	DB	069H
	DB	064H
	DB	065H
	DB	072H
	DB	00H
	DB	00H
	DB	04fH
	DB	06eH
	DB	044H
	DB	075H
	DB	072H
	DB	061H
	DB	074H
	DB	069H
	DB	06fH
	DB	06eH
	DB	043H
	DB	068H
	DB	061H
	DB	06eH
	DB	067H
	DB	065H
	DB	064H
	DB	00H
	DB	06fH
	DB	070H
	DB	065H
	DB	06eH
	DB	042H
	DB	074H
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	070H
	DB	06cH
	DB	061H
	DB	079H
	DB	05fH
	DB	070H
	DB	061H
	DB	075H
	DB	073H
	DB	065H
	DB	042H
	DB	074H
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	DB	073H
	DB	074H
	DB	06fH
	DB	070H
	DB	042H
	DB	074H
	DB	06eH
	DB	05fH
	DB	063H
	DB	06cH
	DB	069H
	DB	063H
	DB	06bH
	DB	065H
	DB	064H
	DB	00H
	ORG $+2
?qt_meta_data_vedio_query@@3QBIB DD 08H			; qt_meta_data_vedio_query
	DD	00H
	DD	00H
	DD	00H
	DD	05H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	027H
	DD	02H
	DD	0aH
	DD	03H
	DD	01H
	DD	02aH
	DD	02H
	DD	0aH
	DD	04H
	DD	00H
	DD	02dH
	DD	02H
	DD	08H
	DD	05H
	DD	00H
	DD	02eH
	DD	02H
	DD	08H
	DD	06H
	DD	00H
	DD	02fH
	DD	02H
	DD	08H
	DD	02bH
	DD	04H
	DD	02H
	DD	02bH
	DD	04H
	DD	02H
	DD	02bH
	DD	02bH
	DD	02bH
	DD	00H
$SG431208 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG431209 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG431210 DB	'qRegisterNormalizedMetaType', 00H
$SG423051 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG423052 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG423053 DB	'qRegisterNormalizedMetaType', 00H
$SG398514 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG398515 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG398516 DB	'qRegisterNormalizedMetaType', 00H
$SG414934 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG414935 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG414936 DB	'qRegisterNormalizedMetaType', 00H
$SG406788 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG406789 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG406790 DB	'qRegisterNormalizedMetaType', 00H
$SG431562 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG431563 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG431564 DB	'qRegisterNormalizedMetaType', 00H
$SG423405 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG423406 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG423407 DB	'qRegisterNormalizedMetaType', 00H
$SG415288 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG415289 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG415290 DB	'qRegisterNormalizedMetaType', 00H
$SG398908 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG398909 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG398910 DB	'qRegisterNormalizedMetaType', 00H
$SG407142 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG407143 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG407144 DB	'qRegisterNormalizedMetaType', 00H
$SG390868 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG390869 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG390870 DB	'qRegisterNormalizedMetaType', 00H
$SG423759 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG423760 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG423761 DB	'qRegisterNormalizedMetaType', 00H
$SG415642 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG415643 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG415644 DB	'qRegisterNormalizedMetaType', 00H
$SG399290 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG399291 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG399292 DB	'qRegisterNormalizedMetaType', 00H
$SG407496 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG407497 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG407498 DB	'qRegisterNormalizedMetaType', 00H
$SG391222 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG391223 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG391224 DB	'qRegisterNormalizedMetaType', 00H
$SG432225 DB	'invalid argument', 00H
	ORG $+3
$SG432226 DB	'%s', 00H
	ORG $+1
$SG424124 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG432227 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Prof'
	DB	'essional\VC\Tools\MSVC\14.26.28801\include\xmemory', 00H
	ORG $+1
$SG424126 DB	'qRegisterNormalizedMetaType', 00H
$SG432228 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'P', 00H, 'r', 00H, 'o', 00H, 'f', 00H, 'e', 00H, 's', 00H
	DB	's', 00H, 'i', 00H, 'o', 00H, 'n', 00H, 'a', 00H, 'l', 00H, '\'
	DB	00H, 'V', 00H, 'C', 00H, '\', 00H, 'T', 00H, 'o', 00H, 'o', 00H
	DB	'l', 00H, 's', 00H, '\', 00H, 'M', 00H, 'S', 00H, 'V', 00H, 'C'
	DB	00H, '\', 00H, '1', 00H, '4', 00H, '.', 00H, '2', 00H, '6', 00H
	DB	'.', 00H, '2', 00H, '8', 00H, '8', 00H, '0', 00H, '1', 00H, '\'
	DB	00H, 'i', 00H, 'n', 00H, 'c', 00H, 'l', 00H, 'u', 00H, 'd', 00H
	DB	'e', 00H, '\', 00H, 'x', 00H, 'm', 00H, 'e', 00H, 'm', 00H, 'o'
	DB	00H, 'r', 00H, 'y', 00H, 00H, 00H
	ORG $+2
$SG432229 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG432230 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+2
$SG424125 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG415996 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG415998 DB	'qRegisterNormalizedMetaType', 00H
$SG415997 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG407850 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG407852 DB	'qRegisterNormalizedMetaType', 00H
$SG407851 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG399672 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG399674 DB	'qRegisterNormalizedMetaType', 00H
$SG399673 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG391575 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG391577 DB	'qRegisterNormalizedMetaType', 00H
$SG391576 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG424478 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG424480 DB	'qRegisterNormalizedMetaType', 00H
$SG424479 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG416351 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG416353 DB	'qRegisterNormalizedMetaType', 00H
$SG416352 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG408204 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG408206 DB	'qRegisterNormalizedMetaType', 00H
$SG408205 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG400054 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG400056 DB	'qRegisterNormalizedMetaType', 00H
$SG400055 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG391928 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG391930 DB	'qRegisterNormalizedMetaType', 00H
$SG391929 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG424832 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG424834 DB	'qRegisterNormalizedMetaType', 00H
$SG424833 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG416705 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG416707 DB	'qRegisterNormalizedMetaType', 00H
$SG416706 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG408558 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG408560 DB	'qRegisterNormalizedMetaType', 00H
$SG408559 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG400436 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG400438 DB	'qRegisterNormalizedMetaType', 00H
$SG400437 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG392256 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG392258 DB	'qRegisterNormalizedMetaType', 00H
$SG392257 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG425186 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG425188 DB	'qRegisterNormalizedMetaType', 00H
$SG425187 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG417060 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG417062 DB	'qRegisterNormalizedMetaType', 00H
$SG417061 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG408916 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG408918 DB	'qRegisterNormalizedMetaType', 00H
$SG408917 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG400818 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG400820 DB	'qRegisterNormalizedMetaType', 00H
$SG400819 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG384469 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384470 DB	'asize >= 0 && asize <= aalloc', 00H
	ORG $+2
$SG384478 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384479 DB	'x->ref.isSharable() || options.testFlag(QArrayData::Unsh'
	DB	'arable)', 00H
$SG384480 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384481 DB	'!x->ref.isStatic()', 00H
	ORG $+1
$SG384494 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384495 DB	'int(d->alloc) == aalloc', 00H
$SG384496 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384497 DB	'isDetached()', 00H
	ORG $+3
$SG384498 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384499 DB	'x == d', 00H
	ORG $+1
$SG384507 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384508 DB	'd->data()', 00H
	ORG $+2
$SG384509 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384510 DB	'uint(d->size) <= d->alloc', 00H
	ORG $+2
$SG384511 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384512 DB	'd != Data::unsharableEmpty()', 00H
	ORG $+3
$SG384513 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384514 DB	'aalloc ? d != Data::sharedNull() : d == Data::sharedNull'
	DB	'()', 00H
	ORG $+1
$SG384515 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384516 DB	'd->alloc >= uint(aalloc)', 00H
	ORG $+3
$SG384517 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qvector.h', 00H
	ORG $+1
$SG384518 DB	'd->size == asize', 00H
	ORG $+3
$SG392732 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG392734 DB	'qRegisterNormalizedMetaType', 00H
$SG392733 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG425540 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG425542 DB	'qRegisterNormalizedMetaType', 00H
$SG425541 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG417414 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG417416 DB	'qRegisterNormalizedMetaType', 00H
$SG417415 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG409270 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG409272 DB	'qRegisterNormalizedMetaType', 00H
$SG409271 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG401200 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG401202 DB	'qRegisterNormalizedMetaType', 00H
$SG401201 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG393060 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG393062 DB	'qRegisterNormalizedMetaType', 00H
$SG393061 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG425894 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG425896 DB	'qRegisterNormalizedMetaType', 00H
$SG425895 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG417768 DB	'D:\QT\5.12.2\MSVC2017\include\QtCore\qmetatype.h', 00H
	ORG $+3
$SG417770 DB	'qRegisterNormalizedMetaType', 00H
$SG417769 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
CONST	ENDS
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@vedio_query@@UBEPBUQMetaObject@@XZ	; vedio_query::metaObject
PUBLIC	?qt_metacast@vedio_query@@UAEPAXPBD@Z		; vedio_query::qt_metacast
PUBLIC	?qt_metacall@vedio_query@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; vedio_query::qt_metacall
PUBLIC	?qt_static_metacall@vedio_query@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; vedio_query::qt_static_metacall
PUBLIC	?staticMetaObject@vedio_query@@2UQMetaObject@@B	; vedio_query::staticMetaObject
EXTRN	_strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QWidget@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QWidget@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	?OnSlider@vedio_query@@QAEX_J@Z:PROC		; vedio_query::OnSlider
EXTRN	?OnDurationChanged@vedio_query@@QAEX_J@Z:PROC	; vedio_query::OnDurationChanged
EXTRN	?openBtn_clicked@vedio_query@@AAEXXZ:PROC	; vedio_query::openBtn_clicked
EXTRN	?play_pauseBtn_clicked@vedio_query@@AAEXXZ:PROC	; vedio_query::play_pauseBtn_clicked
EXTRN	?stopBtn_clicked@vedio_query@@AAEXXZ:PROC	; vedio_query::stopBtn_clicked
EXTRN	__imp_?staticMetaObject@QWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@vedio_query@@2UQMetaObject@@B DB 018H DUP (?) ; vedio_query::staticMetaObject
_BSS	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@vedio_query@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@vedio_query@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@vedio_query@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@vedio_query@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@vedio_query@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'vedio_query::staticMetaObject'', COMDAT
; File D:\liuyu\task\Auxiliary_maintenance\Win32\Debug\moc\moc_vedio_query.cpp
; Line 102
	push	ebp
	mov	ebp, esp
; Line 96
	mov	eax, DWORD PTR __imp_?staticMetaObject@QWidget@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@vedio_query@@2UQMetaObject@@B, eax
; Line 97
	mov	DWORD PTR ?staticMetaObject@vedio_query@@2UQMetaObject@@B+4, OFFSET ?qt_meta_stringdata_vedio_query@@3Uqt_meta_stringdata_vedio_query_t@@B
; Line 98
	mov	DWORD PTR ?staticMetaObject@vedio_query@@2UQMetaObject@@B+8, OFFSET ?qt_meta_data_vedio_query@@3QBIB
; Line 99
	mov	DWORD PTR ?staticMetaObject@vedio_query@@2UQMetaObject@@B+12, OFFSET ?qt_static_metacall@vedio_query@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; vedio_query::qt_static_metacall
; Line 100
	mov	DWORD PTR ?staticMetaObject@vedio_query@@2UQMetaObject@@B+16, 0
; Line 101
	mov	DWORD PTR ?staticMetaObject@vedio_query@@2UQMetaObject@@B+20, 0
	pop	ebp
	ret	0
??__E?staticMetaObject@vedio_query@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'vedio_query::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = -8						; size = 4
__t$1 = -4						; size = 4
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@vedio_query@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; vedio_query::qt_static_metacall
; File D:\liuyu\task\Auxiliary_maintenance\Win32\Debug\moc\moc_vedio_query.cpp
; Line 80
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 81
	cmp	DWORD PTR __c$[ebp], 0
	jne	SHORT $LN1@qt_static_
; Line 82
	mov	eax, DWORD PTR __o$[ebp]
	mov	DWORD PTR __t$1[ebp], eax
; Line 84
	mov	ecx, DWORD PTR __id$[ebp]
	mov	DWORD PTR tv69[ebp], ecx
	cmp	DWORD PTR tv69[ebp], 4
	ja	SHORT $LN1@qt_static_
	mov	edx, DWORD PTR tv69[ebp]
	jmp	DWORD PTR $LN12@qt_static_[edx*4]
$LN5@qt_static_:
; Line 85
	mov	eax, 4
	shl	eax, 0
	mov	ecx, DWORD PTR __a$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	mov	eax, DWORD PTR [edx+4]
	push	eax
	mov	ecx, DWORD PTR [edx]
	push	ecx
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?OnSlider@vedio_query@@QAEX_J@Z		; vedio_query::OnSlider
	jmp	SHORT $LN1@qt_static_
$LN6@qt_static_:
; Line 86
	mov	edx, 4
	shl	edx, 0
	mov	eax, DWORD PTR __a$[ebp]
	mov	ecx, DWORD PTR [eax+edx]
	mov	edx, DWORD PTR [ecx+4]
	push	edx
	mov	eax, DWORD PTR [ecx]
	push	eax
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?OnDurationChanged@vedio_query@@QAEX_J@Z ; vedio_query::OnDurationChanged
	jmp	SHORT $LN1@qt_static_
$LN7@qt_static_:
; Line 87
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?openBtn_clicked@vedio_query@@AAEXXZ	; vedio_query::openBtn_clicked
	jmp	SHORT $LN1@qt_static_
$LN8@qt_static_:
; Line 88
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?play_pauseBtn_clicked@vedio_query@@AAEXXZ ; vedio_query::play_pauseBtn_clicked
	jmp	SHORT $LN1@qt_static_
$LN9@qt_static_:
; Line 89
	mov	ecx, DWORD PTR __t$1[ebp]
	call	?stopBtn_clicked@vedio_query@@AAEXXZ	; vedio_query::stopBtn_clicked
$LN1@qt_static_:
; Line 93
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN12@qt_static_:
	DD	$LN5@qt_static_
	DD	$LN6@qt_static_
	DD	$LN7@qt_static_
	DD	$LN8@qt_static_
	DD	$LN9@qt_static_
?qt_static_metacall@vedio_query@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; vedio_query::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@vedio_query@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; vedio_query::qt_metacall
; _this$ = ecx
; File D:\liuyu\task\Auxiliary_maintenance\Win32\Debug\moc\moc_vedio_query.cpp
; Line 119
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 120
	mov	eax, DWORD PTR __a$[ebp]
	push	eax
	mov	ecx, DWORD PTR __id$[ebp]
	push	ecx
	mov	edx, DWORD PTR __c$[ebp]
	push	edx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacall@QWidget@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	DWORD PTR __id$[ebp], eax
; Line 121
	cmp	DWORD PTR __id$[ebp], 0
	jge	SHORT $LN2@qt_metacal
; Line 122
	mov	eax, DWORD PTR __id$[ebp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 123
	cmp	DWORD PTR __c$[ebp], 0
	jne	SHORT $LN3@qt_metacal
; Line 124
	cmp	DWORD PTR __id$[ebp], 5
	jge	SHORT $LN5@qt_metacal
; Line 125
	mov	eax, DWORD PTR __a$[ebp]
	push	eax
	mov	ecx, DWORD PTR __id$[ebp]
	push	ecx
	mov	edx, DWORD PTR __c$[ebp]
	push	edx
	mov	eax, DWORD PTR _this$[ebp]
	push	eax
	call	?qt_static_metacall@vedio_query@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; vedio_query::qt_static_metacall
	add	esp, 16					; 00000010H
$LN5@qt_metacal:
; Line 126
	mov	ecx, DWORD PTR __id$[ebp]
	sub	ecx, 5
	mov	DWORD PTR __id$[ebp], ecx
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 127
	cmp	DWORD PTR __c$[ebp], 12			; 0000000cH
	jne	SHORT $LN4@qt_metacal
; Line 128
	cmp	DWORD PTR __id$[ebp], 5
	jge	SHORT $LN7@qt_metacal
; Line 129
	mov	edx, 4
	imul	eax, edx, 0
	mov	ecx, DWORD PTR __a$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	mov	DWORD PTR [edx], -1
$LN7@qt_metacal:
; Line 130
	mov	eax, DWORD PTR __id$[ebp]
	sub	eax, 5
	mov	DWORD PTR __id$[ebp], eax
$LN4@qt_metacal:
; Line 132
	mov	eax, DWORD PTR __id$[ebp]
$LN1@qt_metacal:
; Line 133
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@vedio_query@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; vedio_query::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_this$ = -4						; size = 4
__clname$ = 8						; size = 4
?qt_metacast@vedio_query@@UAEPAXPBD@Z PROC		; vedio_query::qt_metacast
; _this$ = ecx
; File D:\liuyu\task\Auxiliary_maintenance\Win32\Debug\moc\moc_vedio_query.cpp
; Line 111
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 112
	cmp	DWORD PTR __clname$[ebp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 113
	push	OFFSET ?qt_meta_stringdata_vedio_query@@3Uqt_meta_stringdata_vedio_query_t@@B+112
	mov	eax, DWORD PTR __clname$[ebp]
	push	eax
	call	_strcmp
	add	esp, 8
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 114
	mov	eax, DWORD PTR _this$[ebp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 115
	mov	ecx, DWORD PTR __clname$[ebp]
	push	ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	DWORD PTR __imp_?qt_metacast@QWidget@@UAEPAXPBD@Z
$LN1@qt_metacas:
; Line 116
	mov	esp, ebp
	pop	ebp
	ret	4
?qt_metacast@vedio_query@@UAEPAXPBD@Z ENDP		; vedio_query::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = -8						; size = 4
_this$ = -4						; size = 4
?metaObject@vedio_query@@UBEPBUQMetaObject@@XZ PROC	; vedio_query::metaObject
; _this$ = ecx
; File D:\liuyu\task\Auxiliary_maintenance\Win32\Debug\moc\moc_vedio_query.cpp
; Line 106
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _this$[ebp], ecx
; Line 107
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	DWORD PTR [eax+24], 0
	je	SHORT $LN3@metaObject
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 4
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	ecx, eax
	call	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
	mov	DWORD PTR tv82[ebp], eax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	mov	DWORD PTR tv82[ebp], OFFSET ?staticMetaObject@vedio_query@@2UQMetaObject@@B ; vedio_query::staticMetaObject
$LN4@metaObject:
	mov	eax, DWORD PTR tv82[ebp]
; Line 108
	mov	esp, ebp
	pop	ebp
	ret	0
?metaObject@vedio_query@@UBEPBUQMetaObject@@XZ ENDP	; vedio_query::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File D:\QT\5.12.2\MSVC2017\include\QtCore\qscopedpointer.h
; Line 117
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 118
	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax]
; Line 119
	mov	esp, ebp
	pop	ebp
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
